let play = "";
let playComputer = "";
let win = false;
let whoWin = false;
let themeSelected = "";
let themeNext = "";
let alertMessage = "";
let Timer = 95;

export const getPlay = () => play;
export const setPlay = (value) => (play = value);
export const getWin = () => win;
export const setWin = (value) => (win = value);
export const getWhoWin = () => whoWin;
export const setWhoWin = (value) => (whoWin = value);
export const getThemeSelected = () => themeSelected;
export const setThemeSelected = (value) => (themeSelected = value);
export const getThemeNext = () => themeNext;
export const setThemeNext = (value) => (themeNext = value);
export const getAlertMessage = () => alertMessage;
export const setAlertMessage = (value) => (alertMessage = value);
export const getTimer = () => Timer;
export const setTimer = (value) => (Timer = value);
export const getPlayComputer = () => playComputer;
export const setPlayComputer = (value) => (playComputer = value);
